name: Create Release & Publish To Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: MavenCentral
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      #      - name: AVD cache
      #        uses: actions/cache@v4
      #        id: avd-cache
      #        with:
      #          path: |
      #            ~/.android/avd/*
      #            ~/.android/adb*
      ##          key: avd-${{ matrix.api-level }}
      #          key: avd-34
      - name: Run connected tests
        #        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            ./gradlew :feature_crypto:connectedAndroidTest --stacktrace
            ./gradlew :feature_crypto:connectedCheck --stacktrace
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
      - name: Setup Version
        id: setup
        run: |
          echo "TAG VERSION: ${{ github.ref_name }}"
          echo "RELEASE NAME: ${GITHUB_REF#refs/tags/v}"
          echo "::set-output name=release_name::${GITHUB_REF#refs/tags/v}"
      - name: Create Release From TAG
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.setup.outputs.release_name }}
          draft: false
          prerelease: false
      - name: Setup Maven Central and GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --dearmor > secret_key.gpg
          ls
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "" >> gradle.properties
          echo "mavenCentralUsername=${{ vars.MAVEN_CENTRAL_TOKEN_USERNAME }}" >> gradle.properties
          echo "" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties
          echo "signing.keyId=${{ vars.GPG_KEY_ID }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.password=${{ secrets.GPG_KEY_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.secretKeyRingFile=../secret_key.gpg" >> gradle.properties
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          cat gradle.properties
      - name: Publish To Maven Central
        run: |
          ./gradlew clean
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          chmod +x update_version.sh
          ./update_version.sh feature_crypto/build.gradle.kts 0.0.1-beta ${{ steps.setup.outputs.release_name }}
          ./gradlew :feature_crypto:publishMavenPublicationToMavenCentralRepository
          
